### PR TITLE
Rewrite UrlGenerator to use inheritance [2]

### PR DESCRIPTION
**Pull request by katafrakt**
Since I have not received any answer in https://github.com/jrgifford/delayed_paperclip/pull/127, here is my pull request with all specs fixed and rebased against master.

### CODE REVIEW

**Comment by ScotterC** [comment]
Thanks @katafrakt! 

@maxim what do you think of these chanegs?

**Comment by maxim** [comment]
@katafrakt hey sorry about #127, too much work too little time. Thanks for rebase, I'll try to review asap.

**Comment by maxim** [comment]
This looks good upon review. I see that `MockInterpolator` from Paperclip specs is still there to check timestamp and escape stuff. :+1: from me.

@ScotterC, would be great if you could do a quick check of  `most_appropriate_url` logic in this PR.

**Comment by adamof** [comment]
Not merge-able

**Comment by katafrakt** [comment]
I rebased master and fixed a bug introduced in #134, so now it's possible to merge.

**Comment by katafrakt** [comment]
Rebased again due to merge conflicts.

@ScotterC any prospects of merging this?

**Comment by ScotterC** [comment]
@katafrakt thanks! This is fantastic and a good start to refactoring a lot of that ugly override logic

**Pull request merged**
