### PR TITLE
Rewrite UrlGenerator to use inheritance

### PR DESCRIPTION
**Pull request by maxim**
This is not finished, but the boolean expressions in UrlGenerator are so messy that I just don't have time to figure out why there are 3 failing specs. The code should work, since I carefully wrote it to do exactly what the old code did (sans monkey-patching). I must move onto other tasks for now. :( Submitting it here to discuss/improve/throwaway in the mean time.

### CODE REVIEW

**Comment by ScotterC** [comment]
Thanks so much for the PR @maxim !  I definitely would like to move away from any use of `alias_method_chain` and this looks like a really good start in that direction.  Do you have any initial ideas for why the tests are failing that I can start from?

**Comment by maxim** [comment]
@ScotterC no, thank *you* so much for maintaining this project. I want to help but have so much to juggle right now. Basically all I did was try to gather all the boolean expressions from `for_with_processed`, `most_appropriate_url_with_processed`, and put them all in my new `most_appropriate_url`. Since there is no more `_with_processed`, I think there might be a forgotten _with_processed method call in specs. That might be an easy fix for one of the specs (2?), just fix the method name in spec. However, there's another failure caused by some weird boolean evaluation, and I couldn't determine whether the test or the code was invalid. In order to determine that one would need to understand intention behind all those boolean checks, and currently I just can't. I see lots of redundant checks, methods check for conditions that are also checked in expressions where the methods are called, and it makes my head hurt. Also the mix of `return false; return false; return true;` code and `||, &&` code makes yet more difficult. I think I could give it another shot if the boolean conditions were cleaned up or wrapped in well-named variables.

**Comment by maxim** [comment]
@ScotterC just took another look, i see that `it "goes up the chain"` spec for timestamp_possible needs to be rewritten, there's no more chain, should just validate on return values, not via `expects`.

**Comment by maxim** [comment]
Another note: we shouldn't test anything in UrlGenerator except `timestamp_possible?` and `most_appropriate_url`, as they're the only interface methods. Other methods are implementation details.

**Comment by ScotterC** [comment]
@maxim agreed on all accounts above.  Thanks for taking the time to elaborate!

**Comment by katafrakt** [comment]
I fixed the specs. They are here: https://github.com/katafrakt/delayed_paperclip/tree/oo_url_generator. Also, it's rebased against current master.

What should I do with that? Make another PR or PR to @maxim's branch?

**Comment by katafrakt** [comment]
Anyone? @ScotterC ? ;)

**Comment by morgoth** [comment]
looks like this one can be closed as https://github.com/jrgifford/delayed_paperclip/issues/146 was merged

**Comment by ScotterC** [comment]
Thanks @morgoth !

**Pull request closed without merging**
